### PR TITLE
Update usb_hw.c

### PR DESCRIPTION
**Pull request by ufocia**
Seems to fix button recognition problem on Linux.
Also, fixes an extra descriptor section if no buttons are present.

### CODE REVIEW

**Comment by ufocia** [comment]
I meant if no axes are present

**Comment by Sagigamil** [comment]
Can you upload the bin so we can enjoy the fix before the next version?

**Comment by ufocia** [comment]
> Can you upload the bin so we can enjoy the fix before the next version?

There is a binary in my fork. It is as is, where is, no warranties, no warranty or merchantability or fitness for particular purpose. In a nutshell you're on your own, at your own risk. If it breaks your hardware, it is your own fault and not mine. No support. I reserve the right to take it down at any point without notice.

**Comment by Sagigamil** [comment]
Hi,
I couldn't find the binary, can you please send me a link?
Thank you,
Sagi

‫בתאריך יום ד׳, 10 במרץ 2021 ב-5:36 מאת ‪ufocia‬‏ ***@***.***
‬‏>:‬

**Comment by reinholdPL** [comment]
https://github.com/ufocia/FreeJoy/releases

**Pull request merged**
