### PR TITLE
AS5048A sensor added, spi glitch removed

### PR DESCRIPTION
**Pull request by gerh**
AS5048 sensor added, removal of spi glitch that caused extra pulses on SPI_SCK.

### CODE REVIEW

**Comment by vostrenkov** [comment]
Hey! I'm working on v1.6.3 and your PR gonna become a part of it. Are you able to resolve conflicts with /dev branch? So I will be able to integrate your changes into my current code

**Comment by gerh** [comment]
I resolved the conflicts and put the code on my /dev branch. The AS sensor works with all other sensors except the TLE5011 as far as I can see, I'm working on this, but don't want you to wait too long. Nice that my code becomes part of the project!

**Comment by gerh** [comment]
Sensors TLE5011 and AS5048A are working together if I leave out lines 120 and 121 in tle5011.c 
( SPI1->CR1 &= ~SPI_CR1_SPE;    while (!SPI1->SR & SPI_SR_RXNE);) 
I don't see any side-effects. Are there? 
I pushed my latest code to my /dev branch

**Comment by vostrenkov** [comment]
Nice, thanks!
I will merge it soon into /dev and make some tests. Unfortunately I dont have this AS sensor in stock but I can test how the new code affect on TLE and others

**Comment by gerh** [comment]
I just found another problem. The AS only works if there is a TLE before the AS (lower pin number). 
It would be great if you can test the effect on the other components. I only have one AS and two TLE's.

**Comment by vostrenkov** [comment]
I'm not able to merge your code from /dev to my /dev in this PR because it has been created from your /master. 
image

I could just take changes from your /dev into mine code but I'd like you to be a github contributor to this project. So you better change PR or place another one for your /dev branch

**Comment by gerh** [comment]
I'm still struggling to find a good way to reset the SPI. Code is still not working.
So I have updated the working code to my master branch, the one that works with the TLE or the AS, but is not working with both at the same time. Will this be ok for you? I'm not sure because I have not worked much with Github.

**Comment by vostrenkov** [comment]
Yeah, thats enough. I will test it out and probably find a way to fix it

**Comment by gerh** [comment]
Think I found it! some more testing and I will push the final code tomorrow to my master branch.

**Comment by vostrenkov** [comment]
No need to hurry too much. I'm working on the project only when I have some free time :)

**Comment by gerh** [comment]
closing this because of continuation in the dev branch

**Pull request closed without merging**
